[package]
name = "auth"
version = "0.1.0"
edition.workspace = true

[dependencies]
proto = { path = "../proto", features = ["auth"] }

clap.workspace = true
tonic.workspace = true
tokio.workspace = true
url.workspace = true
