# This template, when filled out, should be saved to
# 
#   /srv/avalanche-rs/avalanche/config.toml
# 
description = "Avalanche (<your hostname>)"
# TODO: Avalanche doesn't expose a grpc server so
# it doesn't need to send a URI to summit
grpc_address = "http://client.only"

# Which summit do you want this instance to connect to?
[upstream]
host_address = "http://<your summit instance>:5001"
public_key = "<your summit public key>"
role = "hub"

[tracing]
level_filter = "info,avalanche=debug,service=debug"
# compact or json
format = "compact"

# This is used for controlling this instance via the admin 'cli' binary
[admin]
username = "avalanche-rs"
name = "avalanche-rs admin"
email = "<your@email>"
public_key = "<your avalanche public key>"
#
# To generate a private key for an avalanche instance, run:
# 
#   ../target/release/cli key generate -f bytes /srv/avalanche-rs/avalanche/state/.privkey
# 
# To list the public key for use in the public_key field above, run:
# 
#   ../target/release/cli key encode -f bytes /srv/avalanche-rs/avalanche/state/.privkey
#
