[package]
name = "service-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
bitflags.workspace = true
http.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true
