syntax = "proto3";

package vessel;

import "options.proto";
import "google/protobuf/empty.proto";

message UploadRequest {
  bytes chunk = 1;
}

enum Stream {
  STREAM_UNKNOWN = 0;
  STREAM_VOLATILE = 1;
  STREAM_UNSTABLE = 2;
}

message Command {
  message Request {
    string request_id = 1;
    Inner command = 2;
  }

  message Response {
    string request_id = 1;
    bool success = 2;
    optional string error = 3;
  }

  message Inner {
    oneof command {
      vessel.Command.UpdateStream update_stream = 1;
      vessel.Command.AddTag add_tag = 2;
      vessel.Command.RemoveTag remove_tag = 3;
      vessel.Command.FormatUpgrade upgrade_format = 4;
    }
  }

  message UpdateStream {
    string channel = 1;
    Stream stream = 2;
    string version = 3;
  }
  
  message AddTag {
    string channel = 1;
    string tag = 2;
    string history = 3;
  }
  
  message RemoveTag {
    string channel = 1;
    string tag = 2;
  }
  
  message FormatUpgrade {
    string channel = 1;
    UpgradeFormat format = 2;
  }
}

message UpgradeFormat {
  oneof format {
    /// Upgrade from legacy to v0
    UpgradeFormatLegacy legacy = 1;
  }
}

// Upgrade from legacy to v0
message UpgradeFormatLegacy {
  // Tag to create on `legacy` from `volatile`
  // before upgrading `volatile` to `v0`
  string tag_name = 1;
}

service VesselService {
  rpc Upload(stream UploadRequest) returns (google.protobuf.Empty) {
    // Single use token / not session scoped
    option (options.flags) = "ACCESS_TOKEN | NOT_EXPIRED";
    option (options.perm) = "UploadPackage";
  }
}
