description = "Avalanche (test)"
host_address = "http://127.0.0.1:5002"

[tracing]
level_filter = "info,avalanche=debug,service=debug"
# compact or json
format = "compact"

[admin]
username = "admin"
email = "admin@serpentos.com"
public_key = ""

[summit]
host_address = "http://127.0.0.1:5001"
public_key = ""
description = "Avalanche (test)"
admin_name = "admin"
admin_email = "admin@serpentos.com"
role = "hub"

