description = "Summit (test)"
host_address = "http://127.0.0.1:5001"

[tracing]
level_filter = "info,summit=debug,service=debug"
# compact or json
format = "compact"

[admin]
username = "admin"
email = "admin@serpentos.com"
public_key = ""

